ragetool/config/routes.rb
Ragetool::Application.routes.draw do

  root :to => "exercises#index"

  devise_for :users

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :exercise_sessions

  resources :greetings
  resources :exercises do
    resources :submissions
  end
  

end

ragetool/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

ragetool/app/models/exercise.rb
class Exercise < ActiveRecord::Base

  def tag_with_square_brackets
    "[ #{self.tag} ]"
  end

end

ragetool/app/models/exercise_session.rb
class ExerciseSession < ActiveRecord::Base

  validates :room, :length => {:within => 3..10}

  has_many :signups # all signups
  has_many :users, :through => :signups # all users through the join table
end

ragetool/app/models/signup.rb
class Signup < ActiveRecord::Base
  belongs_to :user
  belongs_to :exercise_session
end

ragetool/app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :exercise
end

ragetool/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :submissions
  has_many :signups # all signups
  has_many :exercise_sessions, :through => :signups # all exercise sessions for this user through the join table
  
end

ragetool/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_user!
end

ragetool/app/controllers/exercise_sessions_controller.rb
class ExerciseSessionsController < ApplicationController
  # GET /exercise_sessions
  # GET /exercise_sessions.xml
  def index
    @exercise_sessions = ExerciseSession.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @exercise_sessions }
    end
  end

  # GET /exercise_sessions/1
  # GET /exercise_sessions/1.xml
  def show
    @exercise_session = ExerciseSession.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @exercise_session }
    end
  end

  # GET /exercise_sessions/new
  # GET /exercise_sessions/new.xml
  def new
    @exercise_session = ExerciseSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @exercise_session }
    end
  end

  # GET /exercise_sessions/1/edit
  def edit
    @exercise_session = ExerciseSession.find(params[:id])
  end

  # POST /exercise_sessions
  # POST /exercise_sessions.xml
  def create
    @exercise_session = ExerciseSession.new(params[:exercise_session])

    respond_to do |format|
      if @exercise_session.save
        format.html { redirect_to(@exercise_session, :notice => 'Exercise session was successfully created.') }
        format.xml  { render :xml => @exercise_session, :status => :created, :location => @exercise_session }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @exercise_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /exercise_sessions/1
  # PUT /exercise_sessions/1.xml
  def update
    @exercise_session = ExerciseSession.find(params[:id])

    respond_to do |format|
      if @exercise_session.update_attributes(params[:exercise_session])
        format.html { redirect_to(@exercise_session, :notice => 'Exercise session was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @exercise_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_sessions/1
  # DELETE /exercise_sessions/1.xml
  def destroy
    @exercise_session = ExerciseSession.find(params[:id])
    @exercise_session.destroy

    respond_to do |format|
      format.html { redirect_to(exercise_sessions_url) }
      format.xml  { head :ok }
    end
  end
end

ragetool/app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  skip_before_filter :authenticate_user!

  def index
    @exercises = Exercise.all
    
    respond_to do |format|
      format.xml { render :xml => @exercises.to_xml }
      format.json { render :json => @exercises.to_json }
      format.html
    end
    
  end
  
  def show
    @exercise = Exercise.find(params[:id])
    # if existing?
    @submission = current_user.submissions.find_by_exercise_id(@exercise.id)
    
    # if no submission
    if not @submission
      @submission = Submission.new
    end
    
    respond_to do |format|
      format.xml { render :xml => @exercise.to_xml }
      format.json { render :json => @exercises.to_json }
      format.html
    end
  end
end

ragetool/app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController

  def index
    @string_for_template = "All greetings"
  end

  def show
    @value = $redis.get "greetings:#{params[:id]}"
  end

  def create
    id = @redis.incr 'greeting_id'
    puts id
    puts "greetings:#{id}"
    @redis.set "greetings:#{id}", params[:greeting]
    return id.inspect
  end
  
  def put
    $redis.set params[:id], params[:greeting]
  end
  
  def delete
    keys_deleted = @redis.del params[:key]
    if keys_deleted == 1 # isn't checking for 1 a bit volatile?
      ""
    else
      status 404
    end
  end
  
end

ragetool/app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def create
    submission = current_user.submissions.new(params[:submission])
    submission.exercise_id = params[:exercise_id]
    submission.save!
    
    redirect_to exercises_path
  end
end

ragetool/app/helpers/application_helper.rb
module ApplicationHelper
end

ragetool/app/helpers/exercise_sessions_helper.rb
module ExerciseSessionsHelper
end

ragetool/app/helpers/exercises_helper.rb
module ExercisesHelper
end

ragetool/app/helpers/greetings_helper.rb
module GreetingsHelper
end

ragetool/app/helpers/submissions_helper.rb
module SubmissionsHelper
end

ragetool/app/views/exercise_sessions/_form.html.erb
<%= form_for(@exercise_session) do |f| %>
  <% if @exercise_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise_session.errors.count, "error") %> prohibited this exercise_session from being saved:</h2>

      <ul>
      <% @exercise_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room %><br />
    <%= f.text_field :room %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ragetool/app/views/exercise_sessions/edit.html.erb
<h1>Editing exercise_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise_session %> |
<%= link_to 'Back', exercise_sessions_path %>

ragetool/app/views/exercise_sessions/index.html.erb
<h1>Listing exercise_sessions</h1>

<table>
  <tr>
    <th>Room</th>
    <th>Starts at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exercise_sessions.each do |exercise_session| %>
  <tr>
    <td><%= exercise_session.room %></td>
    <td><%= exercise_session.starts_at %></td>
    <td><%= link_to 'Show', exercise_session %></td>
    <td><%= link_to 'Edit', edit_exercise_session_path(exercise_session) %></td>
    <td><%= link_to 'Destroy', exercise_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exercise session', new_exercise_session_path %>

ragetool/app/views/exercise_sessions/new.html.erb
<h1>New exercise_session</h1>

<%= render 'form' %>

<%= link_to 'Back', exercise_sessions_path %>

ragetool/app/views/exercise_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Room:</b>
  <%= @exercise_session.room %>
</p>

<p>
  <b>Starts at:</b>
  <%= @exercise_session.starts_at %>
</p>

<p>
  <b>Users:</b>
  <% @exercise_session.users.each do |u| %>
    <li><%= u.email %></li>
  <% end %>
</p>

<%= link_to 'Edit', edit_exercise_session_path(@exercise_session) %> |
<%= link_to 'Back', exercise_sessions_path %>

ragetool/app/views/exercises/index.html.erb
<h2>Exercises</h2>

<ul>
  <% for exercise in @exercises %>
    <li><%= link_to exercise.tag_with_square_brackets, exercise_path(exercise) %></li>
  <% end %>
</ul>

ragetool/app/views/exercises/show.html.erb
<h2><%= @exercise.tag %></h2>

<% form_for @submission, :url => exercise_submissions_path(@exercise) do |f| %>
  <%= f.text_area :answer %>
  <%= submit_tag "ok" %>
<% end %>
<hr />

ragetool/app/views/greetings/index.html.erb
<p><%= @string_for_template %></p>

ragetool/app/views/greetings/show.html.erb
<p>Value in Redis: <%= @value %></p>

ragetool/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Ragetool</title>
 <%= stylesheet_link_tag :all %>
 <%= javascript_include_tag :defaults %>
 <%= csrf_meta_tag %>
</head>
<body>

    <% if current_user %>
       <%= current_user.email %> (<%= link_to "logout", destroy_user_session_path, :method => :delete %>)<br/>
          <hr/>
       <% end %>

<%= yield %>

</body>
</html>